GET http://localhost:8080/employees/

###

GET http://localhost:5000/employees/e02

###

POST http://localhost:8080/employees/
Content-Type: application/json

{
    "employeeId": "e02",
    "name": "Ashish",
    "role": "Tech Engineer"
}

###

DELETE http://localhost:5000/employees/e02

